document.getElementById("slider1").addEventListener("click", function() {
    document.getElementById("MJ").classList.remove("off")
    document.getElementById("JsSth").classList.add("off")
    document.getElementById("Shreck").classList.add("off")
    document.getElementById("AdHit").classList.add("off")
    document.getElementById("Masunya").classList.add("off")
    document.getElementById("Sanboy").classList.add("off")
    document.getElementById("slider1").classList.add("on")
    document.getElementById("slider2").classList.remove("on")
    document.getElementById("slider3").classList.remove("on")
    document.getElementById("slider4").classList.remove("on")
    document.getElementById("slider5").classList.remove("on")
    document.getElementById("slider6").classList.remove("on")
})
document.getElementById("slider2").addEventListener("click", function() {
    document.getElementById("MJ").classList.add("off")
    document.getElementById("JsSth").classList.remove("off")
    document.getElementById("Shreck").classList.add("off")
    document.getElementById("AdHit").classList.add("off")
    document.getElementById("Masunya").classList.add("off")
    document.getElementById("Sanboy").classList.add("off")
    document.getElementById("slider1").classList.add("on")
    document.getElementById("slider2").classList.add("on")
    document.getElementById("slider1").classList.remove("on")
    document.getElementById("slider3").classList.remove("on")
    document.getElementById("slider4").classList.remove("on")
    document.getElementById("slider5").classList.remove("on")
    document.getElementById("slider6").classList.remove("on")
})

document.getElementById("slider3").addEventListener("click", function() {
    document.getElementById("MJ").classList.add("off")
    document.getElementById("JsSth").classList.add("off")
    document.getElementById("Shreck").classList.remove("off")
    document.getElementById("AdHit").classList.add("off")
    document.getElementById("Masunya").classList.add("off")
    document.getElementById("Sanboy").classList.add("off")
    document.getElementById("slider3").classList.add("on")
    document.getElementById("slider1").classList.remove("on")
    document.getElementById("slider2").classList.remove("on")
    document.getElementById("slider4").classList.remove("on")
    document.getElementById("slider5").classList.remove("on")
    document.getElementById("slider6").classList.remove("on")
})

document.getElementById("slider4").addEventListener("click", function() {
    document.getElementById("MJ").classList.add("off")
    document.getElementById("JsSth").classList.add("off")
    document.getElementById("Shreck").classList.add("off")
    document.getElementById("AdHit").classList.remove("off")
    document.getElementById("Masunya").classList.add("off")
    document.getElementById("Sanboy").classList.add("off")
    document.getElementById("slider4").classList.add("on")
    document.getElementById("slider1").classList.remove("on")
    document.getElementById("slider2").classList.remove("on")
    document.getElementById("slider3").classList.remove("on")
    document.getElementById("slider5").classList.remove("on")
    document.getElementById("slider6").classList.remove("on")
})

document.getElementById("slider5").addEventListener("click", function() {
    document.getElementById("MJ").classList.add("off")
    document.getElementById("JsSth").classList.add("off")
    document.getElementById("Shreck").classList.add("off")
    document.getElementById("AdHit").classList.add("off")
    document.getElementById("Masunya").classList.remove("off")
    document.getElementById("Sanboy").classList.add("off")
    document.getElementById("slider5").classList.add("on")
    document.getElementById("slider1").classList.remove("on")
    document.getElementById("slider2").classList.remove("on")
    document.getElementById("slider3").classList.remove("on")
    document.getElementById("slider4").classList.remove("on")
    document.getElementById("slider6").classList.remove("on")
})

document.getElementById("slider6").addEventListener("click", function() {
    document.getElementById("MJ").classList.add("off")
    document.getElementById("JsSth").classList.add("off")
    document.getElementById("Shreck").classList.add("off")
    document.getElementById("AdHit").classList.add("off")
    document.getElementById("Masunya").classList.add("off")
    document.getElementById("Sanboy").classList.remove("off")
    document.getElementById("slider6").classList.add("on")
    document.getElementById("slider1").classList.remove("on")
    document.getElementById("slider2").classList.remove("on")
    document.getElementById("slider3").classList.remove("on")
    document.getElementById("slider4").classList.remove("on")
    document.getElementById("slider5").classList.remove("on")
})
